BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "USUARIO" (
	"IDUSUARIO"	INTEGER,
	"NOME"	NVARCHAR(255) NOT NULL,
	"EMAIL"	NVARCHAR(255) NOT NULL UNIQUE,
	"TIPOUSUARIO"	INTEGER NOT NULL,
	"DATACRIACAO"	DATE DEFAULT CURRENT_DATE,
	"IMG"	TEXT,
	PRIMARY KEY("IDUSUARIO" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "ALUNO" (
	"IDUSUARIO"	INTEGER,
	"RA"	NVARCHAR(50) NOT NULL UNIQUE,
	FOREIGN KEY("IDUSUARIO") REFERENCES "USUARIO"("IDUSUARIO") ON DELETE CASCADE,
	PRIMARY KEY("IDUSUARIO")
);
CREATE TABLE IF NOT EXISTS "PROFESSOR" (
	"IDUSUARIO"	INTEGER,
	"IDENTIFICADORPROFISSIONAL"	NVARCHAR(100) NOT NULL UNIQUE,
	FOREIGN KEY("IDUSUARIO") REFERENCES "USUARIO"("IDUSUARIO") ON DELETE CASCADE,
	PRIMARY KEY("IDUSUARIO")
);
CREATE TABLE IF NOT EXISTS "TURMAS" (
	"IDTURMA"	INTEGER,
	"NOMETURMA"	NVARCHAR(100) NOT NULL,
	"IDPROFESSOR_FK"	INTEGER,
	"ANOELETIVO"	INTEGER,
	"SEMESTRE"	INTEGER,
	FOREIGN KEY("IDPROFESSOR_FK") REFERENCES "PROFESSOR"("IDUSUARIO"),
	PRIMARY KEY("IDTURMA" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "ALUNOS_TURMA" (
	"IDTURMA_PK_FK"	INTEGER,
	"IDALUNO_PK_FK"	INTEGER,
	"DATAINGRESSO"	DATE DEFAULT CURRENT_DATE,
	FOREIGN KEY("IDALUNO_PK_FK") REFERENCES "ALUNO"("IDUSUARIO"),
	FOREIGN KEY("IDTURMA_PK_FK") REFERENCES "TURMAS"("IDTURMA"),
	PRIMARY KEY("IDTURMA_PK_FK","IDALUNO_PK_FK")
);
CREATE TABLE IF NOT EXISTS "CONTAINER_PERGUNTAS" (
	"IDCONTAINER"	INTEGER,
	"NOME"	NVARCHAR(255) NOT NULL,
	"DESCRICAO"	TEXT,
	"IDPROFESSOR_FK"	BIGINT,
	FOREIGN KEY("IDPROFESSOR_FK") REFERENCES "PROFESSOR"("IDUSUARIO"),
	PRIMARY KEY("IDCONTAINER" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "PERGUNTA" (
	"IDPERGUNTA_PK"	INTEGER,
	"IDPROFESSOR_FK"	INTEGER,
	"IDCONTAINER_FK"	INTEGER,
	"ENUNCIADO"	TEXT NOT NULL,
	"DIFICULDADE"	NVARCHAR(50),
	"EXPLICACAO_PEDAGOGICA"	TEXT,
	"IMAGEM"	TEXT,
	FOREIGN KEY("IDCONTAINER_FK") REFERENCES "CONTAINER_PERGUNTAS"("IDCONTAINER"),
	FOREIGN KEY("IDPROFESSOR_FK") REFERENCES "PROFESSOR"("IDUSUARIO"),
	PRIMARY KEY("IDPERGUNTA_PK" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "ALTERNATIVAS" (
	"IDALTERNATIVA_PK"	INTEGER,
	"IDPERGUNTA_FK"	INTEGER NOT NULL,
	"ALTERNATIVA"	TEXT NOT NULL,
	"ROTULO"	CHAR(1),
	"CORRETA"	BIT DEFAULT 0,
	FOREIGN KEY("IDPERGUNTA_FK") REFERENCES "PERGUNTA"("IDPERGUNTA_PK") ON DELETE CASCADE,
	PRIMARY KEY("IDALTERNATIVA_PK" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "QUIZ" (
	"IDQUIZ_PK"	INTEGER,
	"IDCRIADOR_FK"	INTEGER,
	"TITULO"	NVARCHAR(255) NOT NULL,
	"CODIGO_PIN"	NVARCHAR(20) UNIQUE,
	"ESTATUS"	BIT DEFAULT 1,
	FOREIGN KEY("IDCRIADOR_FK") REFERENCES "PROFESSOR"("IDUSUARIO"),
	PRIMARY KEY("IDQUIZ_PK" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "QUIZ_PERGUNTA" (
	"IDQUIZ_PK_FK"	INTEGER,
	"IDPERGUNTA_PK_FK"	INTEGER,
	FOREIGN KEY("IDPERGUNTA_PK_FK") REFERENCES "PERGUNTA"("IDPERGUNTA_PK"),
	PRIMARY KEY("IDQUIZ_PK_FK","IDPERGUNTA_PK_FK"),
	FOREIGN KEY("IDQUIZ_PK_FK") REFERENCES "QUIZ"("IDQUIZ_PK")
);
CREATE TABLE IF NOT EXISTS "resultados" (
	"IDRESULTADO"	INTEGER,
	"IDALUNO_FK"	INTEGER,
	"IDQUIZ_FK"	INTEGER,
	"NOTAFINAL"	DECIMAL(5, 2),
	FOREIGN KEY("IDQUIZ_FK") REFERENCES "QUIZ"("IDQUIZ_PK"),
	FOREIGN KEY("IDALUNO_FK") REFERENCES "ALUNO"("IDUSUARIO"),
	PRIMARY KEY("IDRESULTADO" AUTOINCREMENT)
);
INSERT INTO "USUARIO" ("IDUSUARIO","NOME","EMAIL","TIPOUSUARIO","DATACRIACAO","IMG") VALUES (1,'Fabiano Sinhorelli','fabiano.prof@etec.sp.gov.br',1,'2026-05-10',NULL),
 (2,'Elena Ramos','elena.ramos@instituicao.org',1,'2026-05-10',NULL),
 (3,'Lucas Mendes','lucas.mendes@estudante.com',2,'2026-05-10',NULL),
 (4,'Mariana Lima','mari.lima@estudante.com',2,'2026-05-10',NULL),
 (5,'Beatriz Castro','b.castro@estudante.com',2,'2026-05-10',NULL),
 (6,'Vitor Hugo','vitor.hugo@estudante.com',2,'2026-05-10',NULL);
INSERT INTO "ALUNO" ("IDUSUARIO","RA") VALUES (3,'RA260001'),
 (4,'RA260002'),
 (5,'RA260003'),
 (6,'RA260004');
INSERT INTO "PROFESSOR" ("IDUSUARIO","IDENTIFICADORPROFISSIONAL") VALUES (1,'FATEC-2026-01'),
 (2,'FATEC-2026-02');
INSERT INTO "TURMAS" ("IDTURMA","NOMETURMA","IDPROFESSOR_FK","ANOELETIVO","SEMESTRE") VALUES (1,'Desenvolvimento de Sistemas - 4º Semestre',1,2026,1);
INSERT INTO "ALUNOS_TURMA" ("IDTURMA_PK_FK","IDALUNO_PK_FK","DATAINGRESSO") VALUES (1,3,'2026-05-10'),
 (1,4,'2026-05-10'),
 (1,5,'2026-05-10'),
 (1,6,'2026-05-10');
INSERT INTO "CONTAINER_PERGUNTAS" ("IDCONTAINER","NOME","DESCRICAO","IDPROFESSOR_FK") VALUES (1,'Introdução ao IoT','Questões sobre ESP32 e Sensores',1);
INSERT INTO "PERGUNTA" ("IDPERGUNTA_PK","IDPROFESSOR_FK","IDCONTAINER_FK","ENUNCIADO","DIFICULDADE","EXPLICACAO_PEDAGOGICA","IMAGEM") VALUES (1,1,1,'Qual o protocolo de comunicação padrão para o ESP32 enviar dados via Serial?','Média','A comunicação Serial utiliza os pinos TX e RX.',NULL);
INSERT INTO "ALTERNATIVAS" ("IDALTERNATIVA_PK","IDPERGUNTA_FK","ALTERNATIVA","ROTULO","CORRETA") VALUES (1,1,'HTTP','A',0),
 (2,1,'UART/Serial','B',1),
 (3,1,'Bluetooth Low Energy','C',0);
INSERT INTO "QUIZ" ("IDQUIZ_PK","IDCRIADOR_FK","TITULO","CODIGO_PIN","ESTATUS") VALUES (1,1,'Quiz de Revisão Acelera','ACEL26',1);
INSERT INTO "QUIZ_PERGUNTA" ("IDQUIZ_PK_FK","IDPERGUNTA_PK_FK") VALUES (1,1);
INSERT INTO "resultados" ("IDRESULTADO","IDALUNO_FK","IDQUIZ_FK","NOTAFINAL") VALUES (1,3,1,9.5),
 (2,4,1,10);
COMMIT;
